-- MySQL Script generated by MySQL Workbench
-- Tue May 18 21:54:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Testdb` DEFAULT CHARACTER SET utf8 ;
USE `Testdb` ;

-- -----------------------------------------------------
-- Table `Testdb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Testdb`.`Product` (
  `maker` VARCHAR(10) NULL,
  `model` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NULL,
  PRIMARY KEY (`model`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Testdb`.`laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Testdb`.`laptop` (
  `code` INT NOT NULL,
  `speed` SMALLINT NULL,
  `ram` SMALLINT NULL,
  `hd` REAL NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `screen` TINYINT NULL,
  `model` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `mod_idx` (`model` ASC) VISIBLE,
  CONSTRAINT `mod3`
    FOREIGN KEY (`model`)
    REFERENCES `Testdb`.`Product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Testdb`.`printer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Testdb`.`printer` (
  `code` INT NOT NULL,
  `color` CHAR(1) NULL,
  `type` VARCHAR(10) NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `model` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `mod_idx` (`model` ASC) VISIBLE,
  CONSTRAINT `mod2`
    FOREIGN KEY (`model`)
    REFERENCES `Testdb`.`Product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Testdb`.`PC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Testdb`.`PC` (
  `Code` INT NOT NULL,
  `speed` SMALLINT NOT NULL,
  `ram` SMALLINT NOT NULL,
  `hd` REAL NOT NULL,
  `cd` VARCHAR(10) NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `model` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Code`),
  INDEX `mod_idx` (`model` ASC) VISIBLE,
  CONSTRAINT `mod1`
    FOREIGN KEY (`model`)
    REFERENCES `Testdb`.`Product` (`model`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
