-- MySQL Script generated by MySQL Workbench
-- Tue Jun  1 17:25:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel` DEFAULT CHARACTER SET utf8 ;
USE `Hotel` ;

-- -----------------------------------------------------
-- Table `Hotel`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `LocalDate` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Room` (
  `roomID` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` SMALLINT NOT NULL,
  `numberOfStars` TINYINT NOT NULL,
  `floor` TINYINT NOT NULL,
  `status` ENUM('BOOK_ROOM', 'FREE_ROOM', 'ROOM_CLEANING') NULL DEFAULT NULL,
  `numBed` TINYINT NOT NULL,
  `basePrice` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`roomID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Service` (
  `idService` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` TINYTEXT NOT NULL,
  `date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idService`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Guest_has_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Guest_has_Service` (
  `Guest_id` INT NOT NULL,
  `Service_idService` INT NOT NULL,
  PRIMARY KEY (`Guest_id`, `Service_idService`),
  INDEX `fk_Guest_has_Service_Service1_idx` (`Service_idService` ASC) VISIBLE,
  INDEX `fk_Guest_has_Service_Guest_idx` (`Guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_Guest_has_Service_Guest`
    FOREIGN KEY (`Guest_id`)
    REFERENCES `Hotel`.`Guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guest_has_Service_Service1`
    FOREIGN KEY (`Service_idService`)
    REFERENCES `Hotel`.`Service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`Guest_has_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`Guest_has_Room` (
  `Guest_id` INT NOT NULL,
  `Room_roomID` INT NOT NULL,
  PRIMARY KEY (`Guest_id`, `Room_roomID`),
  INDEX `fk_Guest_has_Room_Room1_idx` (`Room_roomID` ASC) VISIBLE,
  INDEX `fk_Guest_has_Room_Guest1_idx` (`Guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_Guest_has_Room_Guest1`
    FOREIGN KEY (`Guest_id`)
    REFERENCES `Hotel`.`Guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guest_has_Room_Room1`
    FOREIGN KEY (`Room_roomID`)
    REFERENCES `Hotel`.`Room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
