-- MySQL Script generated by MySQL Workbench
-- Wed Aug 11 20:30:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Network Social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Network Social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Network Social` DEFAULT CHARACTER SET utf8 ;
USE `Network Social` ;

-- -----------------------------------------------------
-- Table `Network Social`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Role` (
  `idRole` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`User` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `birthday` DATE NOT NULL,
  `Role_idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Role_idRole`),
  INDEX `fk_User_Role1_idx` (`Role_idRole` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `Network Social`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Group` (
  `idGroup` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Post` (
  `idPost` INT NOT NULL,
  `createdDate` DATETIME NOT NULL,
  `title` TEXT NULL,
  `Group_idGroup` INT NOT NULL,
  PRIMARY KEY (`idPost`, `Group_idGroup`),
  INDEX `fk_Post_Group1_idx` (`Group_idGroup` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `Network Social`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Post_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Post_has_User` (
  `Post_idPost` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Post_idPost`, `User_idUser`),
  INDEX `fk_Post_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Post_has_User_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Post_has_User_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `Network Social`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Network Social`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Image` (
  `idImage` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Photo` BLOB NOT NULL,
  PRIMARY KEY (`idImage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Image_has_Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Image_has_Post` (
  `Image_idImage` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`Image_idImage`, `Post_idPost`),
  INDEX `fk_Image_has_Post_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  INDEX `fk_Image_has_Post_Image1_idx` (`Image_idImage` ASC) VISIBLE,
  CONSTRAINT `fk_Image_has_Post_Image1`
    FOREIGN KEY (`Image_idImage`)
    REFERENCES `Network Social`.`Image` (`idImage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Image_has_Post_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `Network Social`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Friends` (
  `User_idUser` INT NOT NULL,
  `User_idFrend` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `User_idFrend`),
  INDEX `fk_User_has_User_User2_idx` (`User_idFrend` ASC) VISIBLE,
  INDEX `fk_User_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Network Social`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`User_idFrend`)
    REFERENCES `Network Social`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Chat` (
  `idChat` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idChat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Message` (
  `idMessage` INT NOT NULL,
  `SendText` TEXT NOT NULL,
  `SendTime` TIMESTAMP NOT NULL,
  `Chat_idChat` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idMessage`, `Chat_idChat`, `User_idUser`),
  INDEX `fk_Message_Chat1_idx` (`Chat_idChat` ASC) VISIBLE,
  INDEX `fk_Message_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Chat1`
    FOREIGN KEY (`Chat_idChat`)
    REFERENCES `Network Social`.`Chat` (`idChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Network Social`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`Chat_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`Chat_has_User` (
  `Chat_idChat` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Chat_idChat`, `User_idUser`),
  INDEX `fk_Chat_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Chat_has_User_Chat1_idx` (`Chat_idChat` ASC) VISIBLE,
  CONSTRAINT `fk_Chat_has_User_Chat1`
    FOREIGN KEY (`Chat_idChat`)
    REFERENCES `Network Social`.`Chat` (`idChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Network Social`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network Social`.`User_has_Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Network Social`.`User_has_Group` (
  `User_idUser` INT NOT NULL,
  `Group_idGroup` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Group_idGroup`),
  INDEX `fk_User_has_Group_Group1_idx` (`Group_idGroup` ASC) VISIBLE,
  INDEX `fk_User_has_Group_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Group_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Network Social`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Group_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `Network Social`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
